# Generated by Django 4.0.1 on 2022-01-28 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='skintype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.skintype'),
        ),
    ]
