# Generated by Django 4.0.1 on 2022-01-27 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subcategory',
            table='sub_categories',
        ),
    ]
