# Generated by Django 4.0.1 on 2022-01-27 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_productoption_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productingredient',
            name='ingredients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='key_ingredients', to='products.keyingredient'),
        ),
        migrations.AlterField(
            model_name='productingredient',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='products.product'),
        ),
    ]
